version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

  load_app:
    build: .  # Usará o Dockerfile no diretório atual
    volumes:
      - .:/app  # Monta o diretório atual no contêiner
    command: ["python", "load.py"]  # Executa load.py

  cases_sql_app:
    build: .  # Usará o mesmo Dockerfile
    volumes:
      - .:/app  # Monta o diretório atual no contêiner
    command: ["python", "cases_sql.py"]  # Executa cases_sql.py

volumes:
  pgdata:
